# Generated by Django 4.2 on 2023-12-05 18:42

from django.db import migrations


# python manage.py makemigrations --empty authentication
def create_groups(apps, schema_migration):
    User = apps.get_model('authentication', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_image = Permission.objects.get(codename='add_image')
    change_image = Permission.objects.get(codename='change_image')
    delete_image = Permission.objects.get(codename='delete_image')
    view_image = Permission.objects.get(codename='view_image')

    creator_permissions = [
        add_image,
        change_image,
        delete_image,
        view_image,
    ]

    creators = Group(name='creators')
    creators.save()

    creators.permissions.set(creator_permissions)
    subscribers = Group(name='subscribers')
    subscribers.save()
    subscribers.permissions.add(view_image)

    for user in User.objects.all():
        if user.role == 'CREATOR':
            creators.user_set.add(user)
        if user.role == 'SUBSCRIBER':
            subscribers.user_set.add(user)


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups)

    ]
